// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuntimeEvents.proto

package org.apache.tez.runtime.internals.api.events;

public final class SystemEventProtos {
  private SystemEventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code TaskFailureTypeProto}
   */
  public enum TaskFailureTypeProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FT_NON_FATAL = 0;</code>
     */
    FT_NON_FATAL(0, 0),
    /**
     * <code>FT_FATAL = 1;</code>
     */
    FT_FATAL(1, 1),
    ;

    /**
     * <code>FT_NON_FATAL = 0;</code>
     */
    public static final int FT_NON_FATAL_VALUE = 0;
    /**
     * <code>FT_FATAL = 1;</code>
     */
    public static final int FT_FATAL_VALUE = 1;


    public final int getNumber() { return value; }

    public static TaskFailureTypeProto valueOf(int value) {
      switch (value) {
        case 0: return FT_NON_FATAL;
        case 1: return FT_FATAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TaskFailureTypeProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TaskFailureTypeProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TaskFailureTypeProto>() {
            public TaskFailureTypeProto findValueByNumber(int number) {
              return TaskFailureTypeProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SystemEventProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final TaskFailureTypeProto[] VALUES = values();

    public static TaskFailureTypeProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TaskFailureTypeProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TaskFailureTypeProto)
  }

  public interface TaskAttemptFailedEventProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string diagnostics = 1;
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    boolean hasDiagnostics();
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    String getDiagnostics();
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    com.google.protobuf.ByteString
        getDiagnosticsBytes();

    // optional .TaskFailureTypeProto task_failure_type = 2;
    /**
     * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
     */
    boolean hasTaskFailureType();
    /**
     * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
     */
    TaskFailureTypeProto getTaskFailureType();
  }
  /**
   * Protobuf type {@code TaskAttemptFailedEventProto}
   */
  public static final class TaskAttemptFailedEventProto extends
      com.google.protobuf.GeneratedMessage
      implements TaskAttemptFailedEventProtoOrBuilder {
    // Use TaskAttemptFailedEventProto.newBuilder() to construct.
    private TaskAttemptFailedEventProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskAttemptFailedEventProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskAttemptFailedEventProto defaultInstance;
    public static TaskAttemptFailedEventProto getDefaultInstance() {
      return defaultInstance;
    }

    public TaskAttemptFailedEventProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskAttemptFailedEventProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              diagnostics_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              TaskFailureTypeProto value = TaskFailureTypeProto.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                taskFailureType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SystemEventProtos.internal_static_TaskAttemptFailedEventProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SystemEventProtos.internal_static_TaskAttemptFailedEventProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskAttemptFailedEventProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TaskAttemptFailedEventProto> PARSER =
        new com.google.protobuf.AbstractParser<TaskAttemptFailedEventProto>() {
      public TaskAttemptFailedEventProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskAttemptFailedEventProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TaskAttemptFailedEventProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string diagnostics = 1;
    public static final int DIAGNOSTICS_FIELD_NUMBER = 1;
    private Object diagnostics_;
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public boolean hasDiagnostics() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public String getDiagnostics() {
      Object ref = diagnostics_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          diagnostics_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDiagnosticsBytes() {
      Object ref = diagnostics_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diagnostics_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .TaskFailureTypeProto task_failure_type = 2;
    public static final int TASK_FAILURE_TYPE_FIELD_NUMBER = 2;
    private TaskFailureTypeProto taskFailureType_;
    /**
     * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
     */
    public boolean hasTaskFailureType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
     */
    public TaskFailureTypeProto getTaskFailureType() {
      return taskFailureType_;
    }

    private void initFields() {
      diagnostics_ = "";
      taskFailureType_ = TaskFailureTypeProto.FT_NON_FATAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDiagnosticsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, taskFailureType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDiagnosticsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, taskFailureType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskAttemptFailedEventProto)) {
        return super.equals(obj);
      }
      TaskAttemptFailedEventProto other = (TaskAttemptFailedEventProto) obj;

      boolean result = true;
      result = result && (hasDiagnostics() == other.hasDiagnostics());
      if (hasDiagnostics()) {
        result = result && getDiagnostics()
            .equals(other.getDiagnostics());
      }
      result = result && (hasTaskFailureType() == other.hasTaskFailureType());
      if (hasTaskFailureType()) {
        result = result &&
            (getTaskFailureType() == other.getTaskFailureType());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDiagnostics()) {
        hash = (37 * hash) + DIAGNOSTICS_FIELD_NUMBER;
        hash = (53 * hash) + getDiagnostics().hashCode();
      }
      if (hasTaskFailureType()) {
        hash = (37 * hash) + TASK_FAILURE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + hashEnum(getTaskFailureType());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskAttemptFailedEventProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptFailedEventProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptFailedEventProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptFailedEventProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptFailedEventProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptFailedEventProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TaskAttemptFailedEventProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TaskAttemptFailedEventProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TaskAttemptFailedEventProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptFailedEventProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TaskAttemptFailedEventProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaskAttemptFailedEventProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TaskAttemptFailedEventProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SystemEventProtos.internal_static_TaskAttemptFailedEventProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SystemEventProtos.internal_static_TaskAttemptFailedEventProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskAttemptFailedEventProto.class, Builder.class);
      }

      // Construct using org.apache.tez.runtime.internals.api.events.SystemEventProtos.TaskAttemptFailedEventProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        diagnostics_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        taskFailureType_ = TaskFailureTypeProto.FT_NON_FATAL;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SystemEventProtos.internal_static_TaskAttemptFailedEventProto_descriptor;
      }

      public TaskAttemptFailedEventProto getDefaultInstanceForType() {
        return TaskAttemptFailedEventProto.getDefaultInstance();
      }

      public TaskAttemptFailedEventProto build() {
        TaskAttemptFailedEventProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TaskAttemptFailedEventProto buildPartial() {
        TaskAttemptFailedEventProto result = new TaskAttemptFailedEventProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.diagnostics_ = diagnostics_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskFailureType_ = taskFailureType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskAttemptFailedEventProto) {
          return mergeFrom((TaskAttemptFailedEventProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskAttemptFailedEventProto other) {
        if (other == TaskAttemptFailedEventProto.getDefaultInstance()) return this;
        if (other.hasDiagnostics()) {
          bitField0_ |= 0x00000001;
          diagnostics_ = other.diagnostics_;
          onChanged();
        }
        if (other.hasTaskFailureType()) {
          setTaskFailureType(other.getTaskFailureType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskAttemptFailedEventProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskAttemptFailedEventProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string diagnostics = 1;
      private Object diagnostics_ = "";
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public boolean hasDiagnostics() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public String getDiagnostics() {
        Object ref = diagnostics_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          diagnostics_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDiagnosticsBytes() {
        Object ref = diagnostics_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          diagnostics_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder setDiagnostics(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        diagnostics_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder clearDiagnostics() {
        bitField0_ = (bitField0_ & ~0x00000001);
        diagnostics_ = getDefaultInstance().getDiagnostics();
        onChanged();
        return this;
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder setDiagnosticsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        diagnostics_ = value;
        onChanged();
        return this;
      }

      // optional .TaskFailureTypeProto task_failure_type = 2;
      private TaskFailureTypeProto taskFailureType_ = TaskFailureTypeProto.FT_NON_FATAL;
      /**
       * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
       */
      public boolean hasTaskFailureType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
       */
      public TaskFailureTypeProto getTaskFailureType() {
        return taskFailureType_;
      }
      /**
       * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
       */
      public Builder setTaskFailureType(TaskFailureTypeProto value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        taskFailureType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .TaskFailureTypeProto task_failure_type = 2;</code>
       */
      public Builder clearTaskFailureType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskFailureType_ = TaskFailureTypeProto.FT_NON_FATAL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskAttemptFailedEventProto)
    }

    static {
      defaultInstance = new TaskAttemptFailedEventProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaskAttemptFailedEventProto)
  }

  public interface TaskAttemptKilledEventProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string diagnostics = 1;
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    boolean hasDiagnostics();
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    String getDiagnostics();
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    com.google.protobuf.ByteString
        getDiagnosticsBytes();
  }
  /**
   * Protobuf type {@code TaskAttemptKilledEventProto}
   */
  public static final class TaskAttemptKilledEventProto extends
      com.google.protobuf.GeneratedMessage
      implements TaskAttemptKilledEventProtoOrBuilder {
    // Use TaskAttemptKilledEventProto.newBuilder() to construct.
    private TaskAttemptKilledEventProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskAttemptKilledEventProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskAttemptKilledEventProto defaultInstance;
    public static TaskAttemptKilledEventProto getDefaultInstance() {
      return defaultInstance;
    }

    public TaskAttemptKilledEventProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskAttemptKilledEventProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              diagnostics_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SystemEventProtos.internal_static_TaskAttemptKilledEventProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SystemEventProtos.internal_static_TaskAttemptKilledEventProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskAttemptKilledEventProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TaskAttemptKilledEventProto> PARSER =
        new com.google.protobuf.AbstractParser<TaskAttemptKilledEventProto>() {
      public TaskAttemptKilledEventProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskAttemptKilledEventProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TaskAttemptKilledEventProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string diagnostics = 1;
    public static final int DIAGNOSTICS_FIELD_NUMBER = 1;
    private Object diagnostics_;
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public boolean hasDiagnostics() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public String getDiagnostics() {
      Object ref = diagnostics_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          diagnostics_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string diagnostics = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDiagnosticsBytes() {
      Object ref = diagnostics_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diagnostics_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      diagnostics_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDiagnosticsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDiagnosticsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskAttemptKilledEventProto)) {
        return super.equals(obj);
      }
      TaskAttemptKilledEventProto other = (TaskAttemptKilledEventProto) obj;

      boolean result = true;
      result = result && (hasDiagnostics() == other.hasDiagnostics());
      if (hasDiagnostics()) {
        result = result && getDiagnostics()
            .equals(other.getDiagnostics());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDiagnostics()) {
        hash = (37 * hash) + DIAGNOSTICS_FIELD_NUMBER;
        hash = (53 * hash) + getDiagnostics().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskAttemptKilledEventProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptKilledEventProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptKilledEventProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptKilledEventProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptKilledEventProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptKilledEventProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TaskAttemptKilledEventProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TaskAttemptKilledEventProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TaskAttemptKilledEventProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptKilledEventProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TaskAttemptKilledEventProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaskAttemptKilledEventProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TaskAttemptKilledEventProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SystemEventProtos.internal_static_TaskAttemptKilledEventProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SystemEventProtos.internal_static_TaskAttemptKilledEventProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskAttemptKilledEventProto.class, Builder.class);
      }

      // Construct using org.apache.tez.runtime.internals.api.events.SystemEventProtos.TaskAttemptKilledEventProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        diagnostics_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SystemEventProtos.internal_static_TaskAttemptKilledEventProto_descriptor;
      }

      public TaskAttemptKilledEventProto getDefaultInstanceForType() {
        return TaskAttemptKilledEventProto.getDefaultInstance();
      }

      public TaskAttemptKilledEventProto build() {
        TaskAttemptKilledEventProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TaskAttemptKilledEventProto buildPartial() {
        TaskAttemptKilledEventProto result = new TaskAttemptKilledEventProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.diagnostics_ = diagnostics_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskAttemptKilledEventProto) {
          return mergeFrom((TaskAttemptKilledEventProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskAttemptKilledEventProto other) {
        if (other == TaskAttemptKilledEventProto.getDefaultInstance()) return this;
        if (other.hasDiagnostics()) {
          bitField0_ |= 0x00000001;
          diagnostics_ = other.diagnostics_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskAttemptKilledEventProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskAttemptKilledEventProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string diagnostics = 1;
      private Object diagnostics_ = "";
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public boolean hasDiagnostics() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public String getDiagnostics() {
        Object ref = diagnostics_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          diagnostics_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDiagnosticsBytes() {
        Object ref = diagnostics_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          diagnostics_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder setDiagnostics(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        diagnostics_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder clearDiagnostics() {
        bitField0_ = (bitField0_ & ~0x00000001);
        diagnostics_ = getDefaultInstance().getDiagnostics();
        onChanged();
        return this;
      }
      /**
       * <code>optional string diagnostics = 1;</code>
       */
      public Builder setDiagnosticsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        diagnostics_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskAttemptKilledEventProto)
    }

    static {
      defaultInstance = new TaskAttemptKilledEventProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaskAttemptKilledEventProto)
  }

  public interface TaskAttemptCompletedEventProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TaskAttemptCompletedEventProto}
   */
  public static final class TaskAttemptCompletedEventProto extends
      com.google.protobuf.GeneratedMessage
      implements TaskAttemptCompletedEventProtoOrBuilder {
    // Use TaskAttemptCompletedEventProto.newBuilder() to construct.
    private TaskAttemptCompletedEventProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskAttemptCompletedEventProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskAttemptCompletedEventProto defaultInstance;
    public static TaskAttemptCompletedEventProto getDefaultInstance() {
      return defaultInstance;
    }

    public TaskAttemptCompletedEventProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskAttemptCompletedEventProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SystemEventProtos.internal_static_TaskAttemptCompletedEventProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SystemEventProtos.internal_static_TaskAttemptCompletedEventProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskAttemptCompletedEventProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<TaskAttemptCompletedEventProto> PARSER =
        new com.google.protobuf.AbstractParser<TaskAttemptCompletedEventProto>() {
      public TaskAttemptCompletedEventProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskAttemptCompletedEventProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<TaskAttemptCompletedEventProto> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskAttemptCompletedEventProto)) {
        return super.equals(obj);
      }
      TaskAttemptCompletedEventProto other = (TaskAttemptCompletedEventProto) obj;

      boolean result = true;
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskAttemptCompletedEventProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptCompletedEventProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptCompletedEventProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskAttemptCompletedEventProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskAttemptCompletedEventProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptCompletedEventProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TaskAttemptCompletedEventProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TaskAttemptCompletedEventProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TaskAttemptCompletedEventProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TaskAttemptCompletedEventProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TaskAttemptCompletedEventProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaskAttemptCompletedEventProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TaskAttemptCompletedEventProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SystemEventProtos.internal_static_TaskAttemptCompletedEventProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SystemEventProtos.internal_static_TaskAttemptCompletedEventProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskAttemptCompletedEventProto.class, Builder.class);
      }

      // Construct using org.apache.tez.runtime.internals.api.events.SystemEventProtos.TaskAttemptCompletedEventProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SystemEventProtos.internal_static_TaskAttemptCompletedEventProto_descriptor;
      }

      public TaskAttemptCompletedEventProto getDefaultInstanceForType() {
        return TaskAttemptCompletedEventProto.getDefaultInstance();
      }

      public TaskAttemptCompletedEventProto build() {
        TaskAttemptCompletedEventProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TaskAttemptCompletedEventProto buildPartial() {
        TaskAttemptCompletedEventProto result = new TaskAttemptCompletedEventProto(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskAttemptCompletedEventProto) {
          return mergeFrom((TaskAttemptCompletedEventProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskAttemptCompletedEventProto other) {
        if (other == TaskAttemptCompletedEventProto.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskAttemptCompletedEventProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskAttemptCompletedEventProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskAttemptCompletedEventProto)
    }

    static {
      defaultInstance = new TaskAttemptCompletedEventProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaskAttemptCompletedEventProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskAttemptFailedEventProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaskAttemptFailedEventProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskAttemptKilledEventProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaskAttemptKilledEventProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskAttemptCompletedEventProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaskAttemptCompletedEventProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023RuntimeEvents.proto\"d\n\033TaskAttemptFail" +
      "edEventProto\022\023\n\013diagnostics\030\001 \001(\t\0220\n\021tas" +
      "k_failure_type\030\002 \001(\0162\025.TaskFailureTypePr" +
      "oto\"2\n\033TaskAttemptKilledEventProto\022\023\n\013di" +
      "agnostics\030\001 \001(\t\" \n\036TaskAttemptCompletedE" +
      "ventProto*6\n\024TaskFailureTypeProto\022\020\n\014FT_" +
      "NON_FATAL\020\000\022\014\n\010FT_FATAL\020\001BC\n+org.apache." +
      "tez.runtime.internals.api.eventsB\021System" +
      "EventProtos\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TaskAttemptFailedEventProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TaskAttemptFailedEventProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaskAttemptFailedEventProto_descriptor,
              new String[] { "Diagnostics", "TaskFailureType", });
          internal_static_TaskAttemptKilledEventProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TaskAttemptKilledEventProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaskAttemptKilledEventProto_descriptor,
              new String[] { "Diagnostics", });
          internal_static_TaskAttemptCompletedEventProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_TaskAttemptCompletedEventProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaskAttemptCompletedEventProto_descriptor,
              new String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
