// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MRRuntimeProtos.proto

package org.apache.tez.mapreduce.protos;

public final class MRRuntimeProtos {
  private MRRuntimeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MRSplitsProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 version = 1;
    /**
     * <code>optional int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 1;</code>
     */
    int getVersion();

    // repeated .MRSplitProto splits = 2;
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> 
        getSplitsList();
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto getSplits(int index);
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    int getSplitsCount();
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    java.util.List<? extends org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder> 
        getSplitsOrBuilderList();
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder getSplitsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MRSplitsProto}
   *
   * <pre>
   * Represents multiple MR splits
   * </pre>
   */
  public static final class MRSplitsProto extends
      com.google.protobuf.GeneratedMessage
      implements MRSplitsProtoOrBuilder {
    // Use MRSplitsProto.newBuilder() to construct.
    private MRSplitsProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MRSplitsProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MRSplitsProto defaultInstance;
    public static MRSplitsProto getDefaultInstance() {
      return defaultInstance;
    }

    public MRSplitsProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MRSplitsProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                splits_ = new java.util.ArrayList<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto>();
                mutable_bitField0_ |= 0x00000002;
              }
              splits_.add(input.readMessage(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          splits_ = java.util.Collections.unmodifiableList(splits_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitsProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MRSplitsProto> PARSER =
        new com.google.protobuf.AbstractParser<MRSplitsProto>() {
      public MRSplitsProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MRSplitsProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MRSplitsProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // repeated .MRSplitProto splits = 2;
    public static final int SPLITS_FIELD_NUMBER = 2;
    private java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> splits_;
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    public java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> getSplitsList() {
      return splits_;
    }
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    public java.util.List<? extends org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder> 
        getSplitsOrBuilderList() {
      return splits_;
    }
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    public int getSplitsCount() {
      return splits_.size();
    }
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto getSplits(int index) {
      return splits_.get(index);
    }
    /**
     * <code>repeated .MRSplitProto splits = 2;</code>
     *
     * <pre>
     * May be useful to have a single large field to serialize all splits
     * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
     * </pre>
     */
    public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder getSplitsOrBuilder(
        int index) {
      return splits_.get(index);
    }

    private void initFields() {
      version_ = 0;
      splits_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      for (int i = 0; i < splits_.size(); i++) {
        output.writeMessage(2, splits_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      for (int i = 0; i < splits_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, splits_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto)) {
        return super.equals(obj);
      }
      org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto other = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && getSplitsList()
          .equals(other.getSplitsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (getSplitsCount() > 0) {
        hash = (37 * hash) + SPLITS_FIELD_NUMBER;
        hash = (53 * hash) + getSplitsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MRSplitsProto}
     *
     * <pre>
     * Represents multiple MR splits
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitsProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitsProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder.class);
      }

      // Construct using org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSplitsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (splitsBuilder_ == null) {
          splits_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          splitsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitsProto_descriptor;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto getDefaultInstanceForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance();
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto build() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto buildPartial() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto result = new org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (splitsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            splits_ = java.util.Collections.unmodifiableList(splits_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.splits_ = splits_;
        } else {
          result.splits_ = splitsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto) {
          return mergeFrom((org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto other) {
        if (other == org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (splitsBuilder_ == null) {
          if (!other.splits_.isEmpty()) {
            if (splits_.isEmpty()) {
              splits_ = other.splits_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSplitsIsMutable();
              splits_.addAll(other.splits_);
            }
            onChanged();
          }
        } else {
          if (!other.splits_.isEmpty()) {
            if (splitsBuilder_.isEmpty()) {
              splitsBuilder_.dispose();
              splitsBuilder_ = null;
              splits_ = other.splits_;
              bitField0_ = (bitField0_ & ~0x00000002);
              splitsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSplitsFieldBuilder() : null;
            } else {
              splitsBuilder_.addAllMessages(other.splits_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 version = 1;
      private int version_ ;
      /**
       * <code>optional int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // repeated .MRSplitProto splits = 2;
      private java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> splits_ =
        java.util.Collections.emptyList();
      private void ensureSplitsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          splits_ = new java.util.ArrayList<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto>(splits_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder> splitsBuilder_;

      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> getSplitsList() {
        if (splitsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(splits_);
        } else {
          return splitsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public int getSplitsCount() {
        if (splitsBuilder_ == null) {
          return splits_.size();
        } else {
          return splitsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto getSplits(int index) {
        if (splitsBuilder_ == null) {
          return splits_.get(index);
        } else {
          return splitsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder setSplits(
          int index, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto value) {
        if (splitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitsIsMutable();
          splits_.set(index, value);
          onChanged();
        } else {
          splitsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder setSplits(
          int index, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder builderForValue) {
        if (splitsBuilder_ == null) {
          ensureSplitsIsMutable();
          splits_.set(index, builderForValue.build());
          onChanged();
        } else {
          splitsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder addSplits(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto value) {
        if (splitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitsIsMutable();
          splits_.add(value);
          onChanged();
        } else {
          splitsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder addSplits(
          int index, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto value) {
        if (splitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitsIsMutable();
          splits_.add(index, value);
          onChanged();
        } else {
          splitsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder addSplits(
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder builderForValue) {
        if (splitsBuilder_ == null) {
          ensureSplitsIsMutable();
          splits_.add(builderForValue.build());
          onChanged();
        } else {
          splitsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder addSplits(
          int index, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder builderForValue) {
        if (splitsBuilder_ == null) {
          ensureSplitsIsMutable();
          splits_.add(index, builderForValue.build());
          onChanged();
        } else {
          splitsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder addAllSplits(
          java.lang.Iterable<? extends org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto> values) {
        if (splitsBuilder_ == null) {
          ensureSplitsIsMutable();
          super.addAll(values, splits_);
          onChanged();
        } else {
          splitsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder clearSplits() {
        if (splitsBuilder_ == null) {
          splits_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          splitsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public Builder removeSplits(int index) {
        if (splitsBuilder_ == null) {
          ensureSplitsIsMutable();
          splits_.remove(index);
          onChanged();
        } else {
          splitsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder getSplitsBuilder(
          int index) {
        return getSplitsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder getSplitsOrBuilder(
          int index) {
        if (splitsBuilder_ == null) {
          return splits_.get(index);  } else {
          return splitsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public java.util.List<? extends org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder> 
           getSplitsOrBuilderList() {
        if (splitsBuilder_ != null) {
          return splitsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(splits_);
        }
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder addSplitsBuilder() {
        return getSplitsFieldBuilder().addBuilder(
            org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.getDefaultInstance());
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder addSplitsBuilder(
          int index) {
        return getSplitsFieldBuilder().addBuilder(
            index, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.getDefaultInstance());
      }
      /**
       * <code>repeated .MRSplitProto splits = 2;</code>
       *
       * <pre>
       * May be useful to have a single large field to serialize all splits
       * and use CodedInputStream to read these efficiently (via a Writable/Hadoop serialization wrapper).
       * </pre>
       */
      public java.util.List<org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder> 
           getSplitsBuilderList() {
        return getSplitsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder> 
          getSplitsFieldBuilder() {
        if (splitsBuilder_ == null) {
          splitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder>(
                  splits_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          splits_ = null;
        }
        return splitsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MRSplitsProto)
    }

    static {
      defaultInstance = new MRSplitsProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MRSplitsProto)
  }

  public interface MRSplitProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string split_class_name = 1;
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    boolean hasSplitClassName();
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    java.lang.String getSplitClassName();
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getSplitClassNameBytes();

    // optional bytes split_bytes = 2;
    /**
     * <code>optional bytes split_bytes = 2;</code>
     */
    boolean hasSplitBytes();
    /**
     * <code>optional bytes split_bytes = 2;</code>
     */
    com.google.protobuf.ByteString getSplitBytes();
  }
  /**
   * Protobuf type {@code MRSplitProto}
   *
   * <pre>
   * Represents a single MRSplit
   * </pre>
   */
  public static final class MRSplitProto extends
      com.google.protobuf.GeneratedMessage
      implements MRSplitProtoOrBuilder {
    // Use MRSplitProto.newBuilder() to construct.
    private MRSplitProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MRSplitProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MRSplitProto defaultInstance;
    public static MRSplitProto getDefaultInstance() {
      return defaultInstance;
    }

    public MRSplitProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MRSplitProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              splitClassName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              splitBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MRSplitProto> PARSER =
        new com.google.protobuf.AbstractParser<MRSplitProto>() {
      public MRSplitProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MRSplitProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MRSplitProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string split_class_name = 1;
    public static final int SPLIT_CLASS_NAME_FIELD_NUMBER = 1;
    private java.lang.Object splitClassName_;
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    public boolean hasSplitClassName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    public java.lang.String getSplitClassName() {
      java.lang.Object ref = splitClassName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          splitClassName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string split_class_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSplitClassNameBytes() {
      java.lang.Object ref = splitClassName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        splitClassName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes split_bytes = 2;
    public static final int SPLIT_BYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString splitBytes_;
    /**
     * <code>optional bytes split_bytes = 2;</code>
     */
    public boolean hasSplitBytes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes split_bytes = 2;</code>
     */
    public com.google.protobuf.ByteString getSplitBytes() {
      return splitBytes_;
    }

    private void initFields() {
      splitClassName_ = "";
      splitBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSplitClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, splitBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSplitClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, splitBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto)) {
        return super.equals(obj);
      }
      org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto other = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto) obj;

      boolean result = true;
      result = result && (hasSplitClassName() == other.hasSplitClassName());
      if (hasSplitClassName()) {
        result = result && getSplitClassName()
            .equals(other.getSplitClassName());
      }
      result = result && (hasSplitBytes() == other.hasSplitBytes());
      if (hasSplitBytes()) {
        result = result && getSplitBytes()
            .equals(other.getSplitBytes());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSplitClassName()) {
        hash = (37 * hash) + SPLIT_CLASS_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSplitClassName().hashCode();
      }
      if (hasSplitBytes()) {
        hash = (37 * hash) + SPLIT_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getSplitBytes().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MRSplitProto}
     *
     * <pre>
     * Represents a single MRSplit
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.Builder.class);
      }

      // Construct using org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        splitClassName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        splitBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRSplitProto_descriptor;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto getDefaultInstanceForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.getDefaultInstance();
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto build() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto buildPartial() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto result = new org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.splitClassName_ = splitClassName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.splitBytes_ = splitBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto) {
          return mergeFrom((org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto other) {
        if (other == org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto.getDefaultInstance()) return this;
        if (other.hasSplitClassName()) {
          bitField0_ |= 0x00000001;
          splitClassName_ = other.splitClassName_;
          onChanged();
        }
        if (other.hasSplitBytes()) {
          setSplitBytes(other.getSplitBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string split_class_name = 1;
      private java.lang.Object splitClassName_ = "";
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public boolean hasSplitClassName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public java.lang.String getSplitClassName() {
        java.lang.Object ref = splitClassName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          splitClassName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSplitClassNameBytes() {
        java.lang.Object ref = splitClassName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          splitClassName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public Builder setSplitClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        splitClassName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public Builder clearSplitClassName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        splitClassName_ = getDefaultInstance().getSplitClassName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string split_class_name = 1;</code>
       */
      public Builder setSplitClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        splitClassName_ = value;
        onChanged();
        return this;
      }

      // optional bytes split_bytes = 2;
      private com.google.protobuf.ByteString splitBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes split_bytes = 2;</code>
       */
      public boolean hasSplitBytes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes split_bytes = 2;</code>
       */
      public com.google.protobuf.ByteString getSplitBytes() {
        return splitBytes_;
      }
      /**
       * <code>optional bytes split_bytes = 2;</code>
       */
      public Builder setSplitBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        splitBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes split_bytes = 2;</code>
       */
      public Builder clearSplitBytes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        splitBytes_ = getDefaultInstance().getSplitBytes();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MRSplitProto)
    }

    static {
      defaultInstance = new MRSplitProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MRSplitProto)
  }

  public interface MRInputUserPayloadProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes configuration_bytes = 1;
    /**
     * <code>optional bytes configuration_bytes = 1;</code>
     */
    boolean hasConfigurationBytes();
    /**
     * <code>optional bytes configuration_bytes = 1;</code>
     */
    com.google.protobuf.ByteString getConfigurationBytes();

    // optional .MRSplitsProto splits = 2;
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    boolean hasSplits();
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto getSplits();
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder getSplitsOrBuilder();

    // optional bool grouping_enabled = 3;
    /**
     * <code>optional bool grouping_enabled = 3;</code>
     */
    boolean hasGroupingEnabled();
    /**
     * <code>optional bool grouping_enabled = 3;</code>
     */
    boolean getGroupingEnabled();

    // optional bool sort_splits_enabled = 4 [default = true];
    /**
     * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
     */
    boolean hasSortSplitsEnabled();
    /**
     * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
     */
    boolean getSortSplitsEnabled();
  }
  /**
   * Protobuf type {@code MRInputUserPayloadProto}
   */
  public static final class MRInputUserPayloadProto extends
      com.google.protobuf.GeneratedMessage
      implements MRInputUserPayloadProtoOrBuilder {
    // Use MRInputUserPayloadProto.newBuilder() to construct.
    private MRInputUserPayloadProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MRInputUserPayloadProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MRInputUserPayloadProto defaultInstance;
    public static MRInputUserPayloadProto getDefaultInstance() {
      return defaultInstance;
    }

    public MRInputUserPayloadProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MRInputUserPayloadProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              configurationBytes_ = input.readBytes();
              break;
            }
            case 18: {
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = splits_.toBuilder();
              }
              splits_ = input.readMessage(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(splits_);
                splits_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              groupingEnabled_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sortSplitsEnabled_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRInputUserPayloadProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRInputUserPayloadProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.Builder.class);
    }

    public static com.google.protobuf.Parser<MRInputUserPayloadProto> PARSER =
        new com.google.protobuf.AbstractParser<MRInputUserPayloadProto>() {
      public MRInputUserPayloadProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MRInputUserPayloadProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MRInputUserPayloadProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes configuration_bytes = 1;
    public static final int CONFIGURATION_BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString configurationBytes_;
    /**
     * <code>optional bytes configuration_bytes = 1;</code>
     */
    public boolean hasConfigurationBytes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes configuration_bytes = 1;</code>
     */
    public com.google.protobuf.ByteString getConfigurationBytes() {
      return configurationBytes_;
    }

    // optional .MRSplitsProto splits = 2;
    public static final int SPLITS_FIELD_NUMBER = 2;
    private org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto splits_;
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    public boolean hasSplits() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto getSplits() {
      return splits_;
    }
    /**
     * <code>optional .MRSplitsProto splits = 2;</code>
     */
    public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder getSplitsOrBuilder() {
      return splits_;
    }

    // optional bool grouping_enabled = 3;
    public static final int GROUPING_ENABLED_FIELD_NUMBER = 3;
    private boolean groupingEnabled_;
    /**
     * <code>optional bool grouping_enabled = 3;</code>
     */
    public boolean hasGroupingEnabled() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool grouping_enabled = 3;</code>
     */
    public boolean getGroupingEnabled() {
      return groupingEnabled_;
    }

    // optional bool sort_splits_enabled = 4 [default = true];
    public static final int SORT_SPLITS_ENABLED_FIELD_NUMBER = 4;
    private boolean sortSplitsEnabled_;
    /**
     * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
     */
    public boolean hasSortSplitsEnabled() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
     */
    public boolean getSortSplitsEnabled() {
      return sortSplitsEnabled_;
    }

    private void initFields() {
      configurationBytes_ = com.google.protobuf.ByteString.EMPTY;
      splits_ = org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance();
      groupingEnabled_ = false;
      sortSplitsEnabled_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, configurationBytes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, splits_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, groupingEnabled_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, sortSplitsEnabled_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, configurationBytes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, splits_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, groupingEnabled_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, sortSplitsEnabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto)) {
        return super.equals(obj);
      }
      org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto other = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto) obj;

      boolean result = true;
      result = result && (hasConfigurationBytes() == other.hasConfigurationBytes());
      if (hasConfigurationBytes()) {
        result = result && getConfigurationBytes()
            .equals(other.getConfigurationBytes());
      }
      result = result && (hasSplits() == other.hasSplits());
      if (hasSplits()) {
        result = result && getSplits()
            .equals(other.getSplits());
      }
      result = result && (hasGroupingEnabled() == other.hasGroupingEnabled());
      if (hasGroupingEnabled()) {
        result = result && (getGroupingEnabled()
            == other.getGroupingEnabled());
      }
      result = result && (hasSortSplitsEnabled() == other.hasSortSplitsEnabled());
      if (hasSortSplitsEnabled()) {
        result = result && (getSortSplitsEnabled()
            == other.getSortSplitsEnabled());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasConfigurationBytes()) {
        hash = (37 * hash) + CONFIGURATION_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getConfigurationBytes().hashCode();
      }
      if (hasSplits()) {
        hash = (37 * hash) + SPLITS_FIELD_NUMBER;
        hash = (53 * hash) + getSplits().hashCode();
      }
      if (hasGroupingEnabled()) {
        hash = (37 * hash) + GROUPING_ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getGroupingEnabled());
      }
      if (hasSortSplitsEnabled()) {
        hash = (37 * hash) + SORT_SPLITS_ENABLED_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getSortSplitsEnabled());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MRInputUserPayloadProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRInputUserPayloadProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRInputUserPayloadProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.class, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.Builder.class);
      }

      // Construct using org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSplitsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        configurationBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (splitsBuilder_ == null) {
          splits_ = org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance();
        } else {
          splitsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        groupingEnabled_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        sortSplitsEnabled_ = true;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.internal_static_MRInputUserPayloadProto_descriptor;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto getDefaultInstanceForType() {
        return org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.getDefaultInstance();
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto build() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto buildPartial() {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto result = new org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.configurationBytes_ = configurationBytes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (splitsBuilder_ == null) {
          result.splits_ = splits_;
        } else {
          result.splits_ = splitsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.groupingEnabled_ = groupingEnabled_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sortSplitsEnabled_ = sortSplitsEnabled_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto) {
          return mergeFrom((org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto other) {
        if (other == org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto.getDefaultInstance()) return this;
        if (other.hasConfigurationBytes()) {
          setConfigurationBytes(other.getConfigurationBytes());
        }
        if (other.hasSplits()) {
          mergeSplits(other.getSplits());
        }
        if (other.hasGroupingEnabled()) {
          setGroupingEnabled(other.getGroupingEnabled());
        }
        if (other.hasSortSplitsEnabled()) {
          setSortSplitsEnabled(other.getSortSplitsEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRInputUserPayloadProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes configuration_bytes = 1;
      private com.google.protobuf.ByteString configurationBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes configuration_bytes = 1;</code>
       */
      public boolean hasConfigurationBytes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes configuration_bytes = 1;</code>
       */
      public com.google.protobuf.ByteString getConfigurationBytes() {
        return configurationBytes_;
      }
      /**
       * <code>optional bytes configuration_bytes = 1;</code>
       */
      public Builder setConfigurationBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        configurationBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes configuration_bytes = 1;</code>
       */
      public Builder clearConfigurationBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        configurationBytes_ = getDefaultInstance().getConfigurationBytes();
        onChanged();
        return this;
      }

      // optional .MRSplitsProto splits = 2;
      private org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto splits_ = org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder> splitsBuilder_;
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public boolean hasSplits() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto getSplits() {
        if (splitsBuilder_ == null) {
          return splits_;
        } else {
          return splitsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public Builder setSplits(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto value) {
        if (splitsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          splits_ = value;
          onChanged();
        } else {
          splitsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public Builder setSplits(
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder builderForValue) {
        if (splitsBuilder_ == null) {
          splits_ = builderForValue.build();
          onChanged();
        } else {
          splitsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public Builder mergeSplits(org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto value) {
        if (splitsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              splits_ != org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance()) {
            splits_ =
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.newBuilder(splits_).mergeFrom(value).buildPartial();
          } else {
            splits_ = value;
          }
          onChanged();
        } else {
          splitsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public Builder clearSplits() {
        if (splitsBuilder_ == null) {
          splits_ = org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.getDefaultInstance();
          onChanged();
        } else {
          splitsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder getSplitsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSplitsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      public org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder getSplitsOrBuilder() {
        if (splitsBuilder_ != null) {
          return splitsBuilder_.getMessageOrBuilder();
        } else {
          return splits_;
        }
      }
      /**
       * <code>optional .MRSplitsProto splits = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder> 
          getSplitsFieldBuilder() {
        if (splitsBuilder_ == null) {
          splitsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProto.Builder, org.apache.tez.mapreduce.protos.MRRuntimeProtos.MRSplitsProtoOrBuilder>(
                  splits_,
                  getParentForChildren(),
                  isClean());
          splits_ = null;
        }
        return splitsBuilder_;
      }

      // optional bool grouping_enabled = 3;
      private boolean groupingEnabled_ ;
      /**
       * <code>optional bool grouping_enabled = 3;</code>
       */
      public boolean hasGroupingEnabled() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool grouping_enabled = 3;</code>
       */
      public boolean getGroupingEnabled() {
        return groupingEnabled_;
      }
      /**
       * <code>optional bool grouping_enabled = 3;</code>
       */
      public Builder setGroupingEnabled(boolean value) {
        bitField0_ |= 0x00000004;
        groupingEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool grouping_enabled = 3;</code>
       */
      public Builder clearGroupingEnabled() {
        bitField0_ = (bitField0_ & ~0x00000004);
        groupingEnabled_ = false;
        onChanged();
        return this;
      }

      // optional bool sort_splits_enabled = 4 [default = true];
      private boolean sortSplitsEnabled_ = true;
      /**
       * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
       */
      public boolean hasSortSplitsEnabled() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
       */
      public boolean getSortSplitsEnabled() {
        return sortSplitsEnabled_;
      }
      /**
       * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
       */
      public Builder setSortSplitsEnabled(boolean value) {
        bitField0_ |= 0x00000008;
        sortSplitsEnabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool sort_splits_enabled = 4 [default = true];</code>
       */
      public Builder clearSortSplitsEnabled() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sortSplitsEnabled_ = true;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MRInputUserPayloadProto)
    }

    static {
      defaultInstance = new MRInputUserPayloadProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MRInputUserPayloadProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MRSplitsProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MRSplitsProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MRSplitProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MRSplitProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MRInputUserPayloadProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MRInputUserPayloadProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MRRuntimeProtos.proto\"?\n\rMRSplitsProto" +
      "\022\017\n\007version\030\001 \001(\005\022\035\n\006splits\030\002 \003(\0132\r.MRSp" +
      "litProto\"=\n\014MRSplitProto\022\030\n\020split_class_" +
      "name\030\001 \001(\t\022\023\n\013split_bytes\030\002 \001(\014\"\223\001\n\027MRIn" +
      "putUserPayloadProto\022\033\n\023configuration_byt" +
      "es\030\001 \001(\014\022\036\n\006splits\030\002 \001(\0132\016.MRSplitsProto" +
      "\022\030\n\020grouping_enabled\030\003 \001(\010\022!\n\023sort_split" +
      "s_enabled\030\004 \001(\010:\004trueB5\n\037org.apache.tez." +
      "mapreduce.protosB\017MRRuntimeProtos\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MRSplitsProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MRSplitsProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MRSplitsProto_descriptor,
              new java.lang.String[] { "Version", "Splits", });
          internal_static_MRSplitProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MRSplitProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MRSplitProto_descriptor,
              new java.lang.String[] { "SplitClassName", "SplitBytes", });
          internal_static_MRInputUserPayloadProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MRInputUserPayloadProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MRInputUserPayloadProto_descriptor,
              new java.lang.String[] { "ConfigurationBytes", "Splits", "GroupingEnabled", "SortSplitsEnabled", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
